### ISSUE TITLE
Bug: FFox: New tab doesn't open the right page when about:blank is set as the brower's home page

### ISSUE THREAD

**Issue by JamesDenholm** [lusakasa/saka-key#115]
As issue title states, under saka-key, FFox won't open a new tab to about:blank, instead opening https://www.google.com/.

Browser inbuilt "New Tab" functionality correctly opens a new tab to about:blank. It should be possible to just use that functionality, right?

**Comment by joefiesta** [comment]
I don't think you can tell Firefox to go to a specific page when you open a new tab.  

Here is Mozilla's explanation of how to customize a new tab:  https://support.mozilla.org/en-US/kb/customize-new-tab-page

It's ridiculous.  

It USED TO BE (I think) that the config entry  "browser.newtab.url" defined the url for a new tab.  (1)  That entry is no longer a part of about:config.  (2)  adding that entry to about:config doesn't change what happens when you open a new tab.  (I suspect adding it does nothing.)

I was a devout lover of CTR (Classic Theme Restorer) addon.   Well, with FF57, CTR doesn't work. (I can't say that for certain.  What I can say, is that at FF54, which is where I am, I have given up using CTR because it breaks more than the good it does.)   CTR has a option to define the URL of a new tab, which worked quite well.  Are you using CTR?   If so, it has probably broken.

**Comment by JamesDenholm** [comment]
Uh, you *certainly* can. Indeed, setting "browser.newtab.url" (which was set to http://www.google.com/, thus probably the source of this... oddity) to about:blank actually causes saka-key to replicate the standard browser behaviour. I'm closing this as a result, but still, it's an odd thing.

**Comment by joefiesta** [comment]
I set "broswer.newtab.url" to https://www.google.com/advanced_search?hl=en.   It doesn't work.

I set "browser.newtab.url" to " http://www.google.com/"    That doesn't work work either.  Nothing I do gets a newtab to open a site.   It you could tell me how to get a tab to open Google, I would be thrilled, because I would like a newtab to do just that:  open google.

**Comment by JamesDenholm** [comment]
Depends on the mechanism you're using, I guess. Or... I might have disabled something in about:config, now that I think about it.

Found it: Do a search for browser.newtabpage, you're probably most interested in enabled and enhanced. I toggled both off.
