### ISSUE TITLE
[Feature request] Launch external application on hinted links

### ISSUE THREAD

**Issue by qoxxxx** [lusakasa/saka-key#143]
Would be very usefull, for example to copy hinted links (xclip ..), play youtube links (mpv/youtube-dl), or anything really. 

Not that I know anything about it, but it could be done according to that comment https://github.com/lusakasa/saka-key/issues/132#issuecomment-345512969

**Comment by alexherbo2** [comment]
Yep I would love to see that in _Saka Key_ and other extensions.

The [native messaging][Native Messaging] is definitely worth investigating.

What prevent to be more used is that the extensions mostly come from the [store][Chrome Web Store].

They’re easily installable, but it’s not the case for an extension using the native messaging.

The setting-up for a native application is not straight-forward, as it requires the user to install the native application a long side the manifest on his machine.

If that feature comes, the way to enable it should be well documented and explained in order to not lost user on obscure features.

[Chrome Web Store]: https://chrome.google.com/webstore
[Native Messaging]: https://developer.chrome.com/apps/nativeMessaging

**Comment by joefiesta** [comment]
This is essentially the same request as #130, and therefore should, I think, be closed.  Yes, it adds making the opening of that external application a function of a hinted link.  But, that opening can only be dictated by a hinted link, hinted element or the URL of the page.  Opening based on any other criterion would have nothing to do with Saka Key.
