### ISSUE TITLE
Outdated documentation regarding hints

### ISSUE THREAD

**Issue by lufte** [lusakasa/saka-key#16]
According to the documentation, the hints command has many variatons which alter the way the element is clicked (Open Link, Open Link in Background Tab, Open Link in Foreground Tab...) and the default binding is `FF`. On the options page though, the default binding is `ALT+F` for opening the link and there's no way (apparently) of invoking the other variations.

**Comment by eejdoowad** [comment]
Hi Lufte, thanks for the feedback. You're probably using either:

**1) the firefox release**

The version on the Firefox marketplace is 12 releases behind because the approval process VERY slow. I was asked to remove the message on the marketplace indicating this. Your best is to install from source following the documentation in the README.

**2) an older version of Saka Key for Chrome**

 The current release is version 1.15. Navigate to "chrome://extensions" and click "Update Extensions Now" in the top right.

**Comment by lufte** [comment]
Oh I see, yes I am effectively using a version installed from firefox addons page. My bad then.

Thanks.
