### ISSUE TITLE
Sometimes the extension stops responding and have to be restarted

### ISSUE THREAD

**Issue by fturcheti** [lusakasa/saka-key#24]
I have no idea what's causing this, but sometimes the extension just stops working on Firefox. To bring it back I have to disable and enable it again – in its own options, not in the addons manager.

Is there something that I can do to help you debug this?

**Comment by lufte** [comment]
Having the same issue here.

**Comment by eejdoowad** [comment]
This one is serious. I'll try to get a fix out ASAP. I suspect that either
* something is corrupting the cached client options stored in the background page or
* something is interfering with messaging options to content scripts

The key-value map of options you specify on the options page aren't sent directly to every content script. Instead, they're transformed, and this transformation is cached in the background page. Content scripts then message the background page to request the cached options.

Saka Key has detailed logging if you compile it in debug mode using 'npm run build:firefox'. Logging will tell you what mode each content script is in, when a script is initialized, when it receives options, when it changes modes and what event triggered the change, and when it sends or receives a message. 

The architecture is a simple state machine with exactly one mode active at any time, but a page is composed of multiple frames, each of which has an independent state machine. 

I'll use Firefox as my daily driver for the next week or so to help iron out issues like this.

**Comment by eejdoowad** [comment]
I've included a screenshot that shows how to interpret the debug logs. When you encounter this bug, check the debug logs for the current mode and the last valid clientOptions that were received. It may be a little confusing since pages may have multiple frames doing their own independent logging.

<img width="790" alt="screen shot 2017-08-24 at 9 14 53 pm" src="https://user-images.githubusercontent.com/2775718/29699812-52fdd8e6-8914-11e7-93cb-6e1048cded30.png">

**Comment by fturcheti** [comment]
Following the install instructions, I've encountered an error executing `npm run build:firefox`. As it referenced `@material`, I tried to upgrade the package `materials-component-web` and voilà! After that I could successfully build the project.

Using this temporary addon I haven't stumble on the described issue, so it seems that the extension generated by this build process is more stable than the other one from the Firefox Addons Developement Channel.

**Comment by eejdoowad** [comment]
The @material error is strange considering the builds at https://travis-ci.org/lusakasa/saka-key pass no problem. I'llgo ahead and upgrade that package just in case. 

It's strange that it only affects the dev  channel build. I haven't change anything since that release that I think would impact this issue. Maybe I'm hiding some important logic behind an 'if (SAKA_DEBUG)', which is only true in non-production builds. 

I'm going to change how the client is loaded in Firefox such that the full client is always loaded into every frame. I suspect this will fix #26, reduce time to first input on heavy pages, and possibly even resolve this issue.

**Comment by eejdoowad** [comment]
Question: when the extension stops is it a particular tab that stops or every tab?

**Comment by lufte** [comment]
For me it stops working on every tab.

**Comment by fturcheti** [comment]
When it stops working, it stops on every tab. But I've seen it not working on specific pages too, like #26.

I can't confirm that this bug only happens with the dev channel build, but I haven't see it for last two days while using the temporary addon I've built. I'll switch to the dev channel build again to see what happens.

**Comment by eejdoowad** [comment]
Version 1.21.2 should hopefully resolve this issue. it's on the firefox dev channel now, and should be on the chrome webstore within a few days (it's been automatically rejected for the second time for not being single purpose). 

I think #24, #27, and #29 are all related to the fact that I broke the logic for how keybindings are generated when I rewrote the options page for release 1.16. 

See commit 37add1114565d41432f2169b603db03156afad83 for the details. The fix was pretty simple.

If your current version is already broken, reset your options using the "Reset All Options button" on the options page. If the problem persists after this reset, please add a comment to #24.

**Comment by fturcheti** [comment]
Thanks, @eejdoowad. It really seems that the last release fixes this issue, so I'm going to close it.
