### ISSUE TITLE
Vimium keybindings on Firefox don't work?

### ISSUE THREAD

**Issue by teranex** [lusakasa/saka-key#27]
I just installed Saka Key 1.19.0rc on Firefox 56.0b6 (Linux, 64bit). Using the 'default' and 'power' keybindings, Saka Key works. But when I switch to the vimium keybindings Saka Key doesn't react to any keypress anymore.

**Comment by eejdoowad** [comment]
I'll take a look tonight. I suspect I added a binding to the vimium profile  without verifying that it didn't conflict with another. If you're binding to characters instead of physical keys, bindings are more likely to conflict.

But it should show an error message above the conflicting binding in either case.

**Comment by teranex** [comment]
I tried enabling/disabling the bind to physical keys option, but that didn't make any difference. I also checked the javascript console but couldn't see any error, but I might be looking in the wrong place for that.

**Comment by eejdoowad** [comment]
Just want to confirm that at some point, I broke the option page logic. Guess tests exist to catch bugs like this. I really should get around to writing some. Working on a fix.

**Comment by eejdoowad** [comment]
Forgot to mention, errors aren't logged to the javascript console in production builds. Don't want to annoy developers who are trying to debug websites.

**Comment by teranex** [comment]
In version 1.20.0rc the 'default' keybinding seems to be broken as well. power still works

**Comment by eejdoowad** [comment]
Version 1.21.2 should hopefully resolve this issue. it's on the firefox dev channel now, and should be on the chrome webstore within a few days (it's been automatically rejected for the second time for not being single purpose). 

I think #24, #27, and #29 are all related to the fact that I broke the logic for how keybindings are generated when I rewrote the options page for release 1.16. 

See commit 37add1114565d41432f2169b603db03156afad83 for the details. The fix was pretty simple.

If your current version is already broken, reset your options using the "Reset All Options button" on the options page. If the problem persists after this reset, please add a comment to #24.

**Comment by teranex** [comment]
It works now indeed. Thanks!
