### ISSUE TITLE
Does not respond to key presses in Firefox

### ISSUE THREAD

**Issue by figdanivi** [lusakasa/saka-key#29]
Upon upgrading to Saka Key 1.20.0, the add-on no longer responds to key presses on any page. I am using Nightly 2017-08-29. I have tried toggling the add-on from the Saka Key's pop-up window, the add-ons manager, and Saka Key's options page.

I don't know where else to begin with troubleshooting, so if you would like me to try anything else or provide further information, let me know.

**Comment by eejdoowad** [comment]
Sorry Firefoxers. I must have botched last night's release somehow. My only excuse is... "it worked on my machine."

This should be a quick fix on my end, soon as I get access again. 

Instituting a better review/testing process is another one for the Todos.

**Comment by PatrickChin** [comment]
I am using Nightly 57.0a1 (2017-08-29) (64-bit) and Saka Key 1.20.0rc. Saka Key does not work unless I change any setting/keybinding in the toolbar and it will work for the rest of the session. This happened with older versions of Saka Key and Firefox too.

**Comment by eejdoowad** [comment]
Hi @PatrickChin, the latest release 1.20.0 modified Saka Key such that for every release after 1.20.0, Saka Key should continue working in all open tabs without requiring any interaction from the user. It's good to know that v1.20.0 isn't fundamentally broken. @figdanivi, have you tried changing a settin?. Any setting. Changing a setting on the options page will trigger Saka Key clients on all open tabs to reset. 

My next release will focus on making specifying and propogating options more stable. It'll hopefully resolve all the recent issues that have been posted about Saka Key breaking.

**Comment by figdanivi** [comment]
@eejdoowad That does not work.

**Comment by eejdoowad** [comment]
@figdanivi, can you try hitting the "Reset All Options button?"

**Comment by figdanivi** [comment]
That fixes it. Even after restoring my options, Saka Key continues to be responsive.

**Comment by eejdoowad** [comment]
Version 1.21.2 should hopefully resolve this issue. it's on the firefox dev channel now, and should be on the chrome webstore within a few days (it's been automatically rejected for the second time for not being single purpose). 

I think #24, #27, and #29 are all related to the fact that I broke the logic for how keybindings are generated when I rewrote the options page for release 1.16. 

See commit 37add1114565d41432f2169b603db03156afad83 for the details. The fix was pretty simple.

If your current version is already broken, reset your options using the "Reset All Options button" on the options page. If the problem persists after this reset, please add a comment to #24.
