### ISSUE TITLE
Saka key removed from Firefox add-on store?

### ISSUE THREAD

**Issue by rleppink** [lusakasa/saka-key#293]
The page on the Firefox add-on store seems to have been removed;
https://addons.mozilla.org/en-US/firefox/addon/saka-key/

Searching for "saka key" in that same store doesn't turn up any other page either;
https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=saka%20key

The Chrome page still seems to be there. What is going wrong here? Can we get it back up?

**Comment by nikbrunner** [comment]
Yes I noticed that too. We need it back! 😊

**Comment by UnPassive** [comment]
Still no news as to why it's removed? I was just about to add it to Firefox on my fresh arch install...

**Comment by NikosEfthias** [comment]
I am now building it by myself seems the team is focusing on the project named saka instead
Funny thing is that on saka there are also keybindings setter however it states that it is not possible to change keymappings in firefox :)

**Comment by rleppink** [comment]
> seems the team is focusing on the project named saka instead

I doubt that, @NikosEfthias, as Saka has always existed but has different functionality altogether (pretty much browser-wide search).

> I am now building it by myself 

Also note, this is not necessary. On the releases page you can download and use the latest release; https://github.com/lusakasa/saka-key/releases

**Comment by NikosEfthias** [comment]
Oh I didnt know about the releases :D thanks

**Comment by wm4** [comment]
This thing is dead, isn't it?

**Comment by NikosEfthias** [comment]
I moved onto vim vixen its not as nice but does the job

**Comment by shawntax** [comment]
Yup, not a great look from Sufyan and team. 

For those installing the latest release `.zip`, don't forget to [allow unsigned add-ons](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users): 

`about:config` > set `xpinstall.signatures.required` to false

**Comment by bovine3dom** [comment]
@odelucca you can't do this in regular Firefox. See https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ and "What are my options if I want to install unsigned extensions in Firefox?". Alternatively, your Linux distribution might have their own procedure for installing unsigned extensions.

**Comment by odelucca** [comment]
I see, thanks.

Are they going to publish it again to the addon store?

**Comment by bovine3dom** [comment]
I've no idea. Two of the maintainers are not active on GitHub and the other one has the characteristic commit activity of someone who actually gets paid to do programming.

---

If anyone currently has saka-key installed on Firefox, they can upload XPI file somewhere and give it to other people:

1. Visit `about:support` and click "Open Folder" next to profile folder
2. Open the extensions folder
3. Find the XPI file that corresponds to saka-key:
    - Either it will have a nice human readable name like saka@saka.io.xpi,
    - Or it will have a horrible UUID like `{455D905A-D37C-4643-A9E2-F6FEFAA0424A}.xpi`. If this is the case, just open them with Firefox until you find the right one.
4. Upload it for everyone to enjoy.

Then, once that XPI file has been uploaded, to install it, just download it and open it with Firefox. It will have been signed by Mozilla so wouldn't require you to install a different version of Firefox. You can check that it's really saka-key by unzipping the XPI file, deleting the META-INF folder and then doing a diff with the saka-key releases on this page.

__NB:__ Mozilla wouldn't have delisted the extension for no reason. It could have serious (but unintentional) security issues. In the past, extensions have been delisted for relatively [minor disagreements](https://github.com/tridactyl/tridactyl/issues/1800). You might want to think twice before installing saka-key (or continuing to use it).

**Comment by wm4** [comment]
Why is Mozilla trying to hard to prevent people from having control over their computer (even on a PC) with this stalinist almost-DRM bullshit of not allowing the user to install any extension they like, but have absolutely no transparency over why an extension got delisted, and possibly endangering users who have it still installed? This doesn't make any sense.

Anyway, the only reason I've even found out that this extension is not on anymore is because Firefox 76 often "freezes" when you try Saka Key on a page. It doesn't actually freeze, but it doesn't respond to most keyboard input. You can only close the tab.

**Comment by wm4** [comment]
While we're at it: Saka key isn't really ideal for keyboard control. It's better than builtin firefox "caret browsing" but worse than just being able to jump between links with the cursor keys. If anyone knows alternative extensions, please do tell.

**Comment by bovine3dom** [comment]
> Anyway, the only reason I've even found out that this extension is not on anymore is because Firefox 76 often "freezes" when you try Saka Key on a page.

Has Mozilla confirmed that somewhere? That would be useful information for people to know. The review process is a little opaque (to people who are not the developers) but they do at least publically explain why extensions have been blocked (but not those which are delisted) here: https://bugzilla.mozilla.org/buglist.cgi?product=Toolkit&component=Blocklist%20Policy%20Requests

I don't think extensions can stay delisted forever - they either get blocked or reinstated, so it is transparent eventually.

---

There are loads of alternative extensions, in no particular order:

https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/ - most popular. Keep it simple.

https://addons.mozilla.org/en-GB/firefox/addon/surfingkeys_ff/ - neat integrated fake Vim.

https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/ - nice but the lead maintainer keeps linking to his extension on other people's repositories

https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/ - somewhere between Vimium and Tridactyl in terms of complexity

https://addons.mozilla.org/en-GB/firefox/addon/linkhints/ - new, simple extension made by Lydell who made VimFx.

https://github.com/alexherbo2/krabby - neat but weird and you need to build it yourself.

There's also [qutebrowser](https://qutebrowser.org/) if you feel like ditching Firefox completely.

**Comment by wm4** [comment]
> Has Mozilla confirmed that somewhere? That would be useful information for people to know. 

Well, if you really meant to quote me, I'm merely a user of Firefox/Saka Key, and I'm only describing what I'm observing, These "freezes" (actually probably some obscure key event propagation problem?) do happen to me, although I'm not sure when exactly this started to happen. Fairly annoying. In Firefox' addon list, there's nothing unusual, except that loading the release notes fails with no specific error given. The addon page for this extension is essentially 404.

A statement from the maintainers would be nice, but if they intended to make one, they'd have made one a month ago.

> The review process is a little opaque (to people who are not the developers) but they do at least publicly explain why extensions have been blocked (but not those which are delisted) here

Well that's reassuring.

> I don't think extensions can stay delisted forever - they either get blocked or reinstated, so it is transparent eventually.

In any case, the way Firefox handles these things seems a bit... machiavellan.

**Comment by alexherbo2** [comment]
@wm4 [Big Pile of Vim-like]

[Big Pile of Vim-like]: https://vim.reversed.top

**Comment by shawntax** [comment]
> Why is Mozilla trying to hard to prevent people from having control over their computer (even on a PC) with this stalinist almost-DRM bullshit of not allowing the user to install any extension they like, but have absolutely no transparency over why an extension got delisted, and possibly endangering users who have it still installed? This doesn't make any sense.

@wm4 Mozilla is not preventing you from controlling your computer in any way. [Add-on Signing](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) helps prevent malicious extensions from getting published, and from Firefox users installing them. Like @bovine3dom mentioned: if Firefox took it down, there is likely a _reason_. Whether that reason is valid or not is a different issue.

Have you also stopped to consider the possibility that the Saka Key team removed the add-on themselves, and that Mozilla may have had nothing to do with it? Whether at the hands of Mozilla or otherwise, it is the Saka Key team's fault for the lack of transparency.

And one more thing. This is not "endangering" users; It is an inconvenience. This is not "stalinist" or "machiavellian". Stalin killed millions of people. You're no longer able to use an extension on one of your browsers. Your choice of words matter, and currently you sound like a petulant child.

**Comment by wm4** [comment]
> @wm4 Mozilla is not preventing you from controlling your computer in any way. 

That is technically correct. They merely force me to get another build of Firefox that allows me to install the extensions I want. So if I want a normal build that can do that, I need to build it myself, which is probably not a thing that can be recommended. In general, it clearly aims to take away control from normal users.

> Add-on Signing helps prevent malicious extensions from getting published, and from Firefox users installing them. 

It mainly prevents installing unsigned extensions. Why would unsigned extensions be more malicious than signed ones? The reality of software signing in general doesn't confirm this. Not providing an extensions mechanism at all would improve user security much more. Not implementing JavaScript for websites also would.

> Like @bovine3dom mentioned: if Firefox took it down, there is likely a reason. Whether that reason is valid or not is a different issue.

Where can I see that reason? Why is Firefox deciding whether a user should or should not be allowed to install a third party thing? Are these not justified questions? Why are you somehow objecting to me asking?

> Have you also stopped to consider the possibility that the Saka Key team removed the add-on themselves, and that Mozilla may have had nothing to do with it? Whether at the hands of Mozilla or otherwise, it is the Saka Key team's fault for the lack of transparency.

The idea that the extension might have been delisted isn't even from me. If you want to hear my opinion (apparently?), Mozilla could for example have displayed that the extension was deleted, instead of showing a generic not found message. As it was noted, Mozilla does delist extensions for various issues. But if that is true, someone searching for the extension on the Mozilla addon website would never know that an extension was removed for security reasons, for all the user knows they could have misspelled the search term. Isn't that bad? "Eventual transparency" (what a wonderful word) was mentioned.

I don't doubt there's something wrong with the Saka team, them not even commenting on this issue.

> And one more thing. This is not "endangering" users; It is an inconvenience.

If they just sweep extensions with security issues under the rug, it certainly sounds like they're potentially endangering users by not disclosing what happened. Again, a user searching the Mozilla addon website will not find anything. Unless Mozilla "eventually" puts up a notice (I don't know whether they do).

> This is not "stalinist" or "machiavellian". Stalin killed millions of people. You're no longer able to use an extension on one of your browsers. Your choice of words matter, and currently you sound like a petulant child.

What does Stalin's mass murdering have to do with anything? Totalitarianism does, though. In my opinion, this attitude Mozilla and other software companies have about "protecting" users, and taking away control from users and transferring it to some of the most powerful corporations on this world (not Mozilla, but they're just imitating Apple/Google/MS anyway), and all "in the best interest" of the user (because the user is a passive consumer who needs to be protected, and also an idiot who doesn't know what's good for them) does have significant potential for dystopian developments.

Anyway, currently I do not need to install Saka. It is still installed where I need it.

**Comment by matheusfillipe** [comment]
So is this really dead?

**Comment by eejdoowad** [comment]
Hi everyone, sorry for missing this, and thanks to the user who informed me by email.

The responsibility for Saka Key getting delisted from the Firefox Marketplace is entirely mine. A while back, I received an email from a Firefox Addon reviewer about how to reproduce the build, since they were unable to. I missed this email, and the multiple followups they sent (which warned that the extension would be delisted).  The deadline arrived and passed by, and the result is what you all know.

I'm working on getting Saka Key reinstated. It probably won't happen immediately since there is, for good reason, a review 'process'.

Also, I am not the most active maintainer, and I'm looking for someone who wants to become a new steward of the project.

**Comment by matheusfillipe** [comment]
> Hi everyone, sorry for missing this, and thanks to the user who informed me by email.
> 
> The responsibility for Saka Key getting delisted from the Firefox Marketplace is entirely mine. A while back, I received an email from a Firefox Addon reviewer about how to reproduce the build, since they were unable to. I missed this email, and the multiple followups they sent (which warned that the extension would be delisted). The deadline arrived and passed by, and the result is what you all know.
> 
> I'm working on getting Saka Key reinstated. It probably won't happen immediately since there is, for good reason, a review 'process'.
> 
> Also, I am not the most active maintainer, and I'm looking for someone who wants to become a new steward of the project.

Ah how good is to hear this! I was thinking this project was abandoned! I coulnt find a better replacement that was so easy to setup as this between multiple devices and this is also what I'm used with anyway.

I really hope this project can continue!

**Comment by eejdoowad** [comment]
It’s back. 🎉🎊🎂
